import { z } from 'zod';
import { runWorkspaceTool } from '../../core/toolRunner.js';
import { inferFileStructure, jsonProfile, patchFileLines, queryJson, queryTable, queryTableAggregate, readAround, readFileChunk, readFileLinesLarge, sampleFile, searchFile, tableProfile, updateTableRows } from '../../tools/largeFiles.js';
import { READ_ONLY, TOOL_RESULT_OUTPUT_SCHEMA, WRITE_FILE } from './annotations.js';
import type { RegisterContext } from './types.js';

const stringRecord = z.record(z.string(), z.string());
const unknownRecord = z.record(z.string(), z.unknown());

export function registerLargeFileTools({ server, config, workspaces }: RegisterContext): void {
  server.registerTool('infer_file_structure', readSpec('Infer file structure', { path: z.string().min(1) }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'infer_file_structure', (w) => inferFileStructure(config, w, args.path)));
  server.registerTool('sample_file', readSpec('Sample file', { path: z.string().min(1), mode: z.string().optional(), head_lines: z.number().int().positive().optional(), tail_lines: z.number().int().positive().optional(), random_lines: z.number().int().nonnegative().optional(), max_bytes: z.number().int().positive().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'sample_file', (w) => sampleFile(config, w, args.path, args.mode, args.head_lines, args.tail_lines, args.random_lines, args.max_bytes)));
  server.registerTool('read_file_chunk', readSpec('Read file chunk', { path: z.string().min(1), offset: z.number().int().nonnegative().optional(), max_bytes: z.number().int().positive().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'read_file_chunk', (w) => readFileChunk(config, w, args.path, args.offset, args.max_bytes)));
  server.registerTool('read_file_lines', readSpec('Read file lines', { path: z.string().min(1), start_line: z.number().int().positive().optional(), max_lines: z.number().int().positive().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'read_file_lines', (w) => readFileLinesLarge(config, w, args.path, args.start_line, args.max_lines)));
  server.registerTool('read_around', readSpec('Read around line', { path: z.string().min(1), line: z.number().int().positive(), before: z.number().int().nonnegative().optional(), after: z.number().int().nonnegative().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'read_around', (w) => readAround(config, w, args.path, args.line, args.before, args.after)));
  server.registerTool('search_file', readSpec('Search one file', { path: z.string().min(1), query: z.string().min(1), max_matches: z.number().int().positive().optional(), context_lines: z.number().int().nonnegative().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'search_file', (w) => searchFile(config, w, args.path, args.query, args.max_matches, args.context_lines)));
  server.registerTool('table_profile', readSpec('Profile table', { path: z.string().min(1), columns: z.array(z.string()).optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'table_profile', (w) => tableProfile(config, w, args.path, args.columns)));
  server.registerTool('query_table', readSpec('Query table', { path: z.string().min(1), select: z.array(z.string()).optional(), where: unknownRecord.optional(), sort: z.array(stringRecord).optional(), limit: z.number().int().positive().optional(), offset: z.number().int().nonnegative().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'query_table', (w) => queryTable(config, w, args.path, args.select, args.where, args.sort, args.limit, args.offset)));
  server.registerTool('query_table_aggregate', readSpec('Aggregate table', { path: z.string().min(1), group_by: z.array(z.string()).optional(), metrics: z.array(stringRecord).optional(), where: unknownRecord.optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'query_table_aggregate', (w) => queryTableAggregate(config, w, args.path, args.group_by, args.metrics, args.where)));
  server.registerTool('json_profile', readSpec('Profile JSON', { path: z.string().min(1), depth: z.number().int().positive().optional(), array_samples: z.number().int().nonnegative().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'json_profile', (w) => jsonProfile(config, w, args.path, args.depth, args.array_samples)));
  server.registerTool('query_json', readSpec('Query JSON', { path: z.string().min(1), query: z.string().min(1), max_bytes: z.number().int().positive().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'query_json', (w) => queryJson(config, w, args.path, args.query, args.max_bytes)));
  server.registerTool('patch_file_lines', writeSpec('Patch file lines', { path: z.string().min(1), start_line: z.number().int().positive(), end_line: z.number().int().positive().optional(), replacement: z.string(), expected_sha256: z.string().optional(), dry_run: z.boolean().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'patch_file_lines', (w) => patchFileLines(config, w, args.path, args.start_line, args.end_line ?? args.start_line, args.replacement, args.expected_sha256, args.dry_run !== false)));
  server.registerTool('update_table_rows', writeSpec('Update table rows', { path: z.string().min(1), where: unknownRecord.optional(), set: stringRecord, dry_run: z.boolean().optional(), allow_multiple: z.boolean().optional() }), async (args: any) => runWorkspaceTool(workspaces, args.workspace_id, 'update_table_rows', (w) => updateTableRows(config, w, args.path, args.where ?? {}, args.set, args.dry_run !== false, Boolean(args.allow_multiple))));
}

function readSpec(title: string, inputSchema: z.ZodRawShape) {
  return { title, description: `${title} within the configured workspace/host filesystem scope.`, inputSchema: { workspace_id: z.string(), ...inputSchema }, outputSchema: TOOL_RESULT_OUTPUT_SCHEMA, annotations: READ_ONLY };
}
function writeSpec(title: string, inputSchema: z.ZodRawShape) {
  return { title, description: `${title} within the configured workspace/host filesystem scope.`, inputSchema: { workspace_id: z.string(), ...inputSchema }, outputSchema: TOOL_RESULT_OUTPUT_SCHEMA, annotations: WRITE_FILE };
}
